spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/statemachine_disruptor?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

  redis:
    host: redis://172.16.6.52:6379
    password: baoxian2019
    database: 6

    data:
      mongodb:
        uri: mongodb://172.16.4.100:27017/article
